version: 1
services:
  - type: web
    name: diplreact-Frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
